version: '3'

services:
  db:
    image: mongo
    volumes:
      - ./db/backup/:/mongo/backup/
      - ./db/bootstrap.sh:/docker-entrypoint-initdb.d/bootstrap.sh
    ports:
      - 27017:27017

  api:
    build:
      context: ./api/
    command: bash -c "/go/src/api/api"
    environment:
      - DOCKER_ENV=true
    ports:
      - 3001:3001
    links:
      - db
    depends_on:
      - db

  client:
    build:
      context: ./client/
    command: bash -c "npm start"
    environment:
      - DOCKER_ENV=true
      - NODE_ENV=development
    ports:
      - 3000:3000
    links:
      - api
    depends_on:
      - db
      - api
