version: '3'

services:
  db:
    image: mongo
    volumes:
      - ./db/backup/:/mongo/backup/
      - ./db/bootstrap.sh:/docker-entrypoint-initdb.d/bootstrap.sh
    ports:
      - 27017:27017

  go:
    build:
      context: ./api/
    volumes:
      - ./api/:/go/src/api/
    links:
      - db
    depends_on:
      - db

  react:
    build:
      context: ./client/
    volumes:
      - ./client/:/client/
    links:
      - api
    depends_on:
      - db
      - api

  api:
    image: dockerized-rest-api_go
    command: bash -c "/go/src/api/api"
    environment:
      - DOCKER_ENV=true
    ports:
      - 3001:3001

  client:
    image: dockerized-rest-api_react
    environment:
      - DOCKER_ENV=true
      - NODE_ENV=development
    command: bash -c "npm start"
    ports:
      - 3000:3000
